export const CURRENTADDRESS = 'CURRENTADDRESS' // 定位信息
export const USER = 'USER' // 用户信息
export const SETTOKEN = 'SETTOKEN' // 设置token
export const REMOVETOKEN = 'REMOVETOKEN' // 删除token
export const USERADDRESS = 'USERADDRESS' // 用户当前编辑地址信息
export const SETUSERADDRESS = 'SETUSERADDRESS' // 更新当前用户地址信息
export const REMOVEUSERADDRESS = 'REMOVEUSERADDRESS' // 清空用户地址信息
export const GETUSERADDRESSLIST = 'GETUSERADDRESSLIST' // 获取用户收货地址列表
export const BATCHFILTER = 'BATCHFILTER ' // 首页筛选条数据
export const UPNAVSORT = 'UPNAVSORT' // 更新首页综合筛选
export const UPDISTANCE = 'UPDISTANCE' // 更新距离最近
export const UPSALES = 'UPSALES' // 更新销量最高
export const UPFILTER = 'UPFILTER' // 更新筛选条件
export const SHOPPARAMS = 'SHOPPARAMS' // 设置商家列表请求参数
export const CATEGORIESPAGE = 'CATEGORIESPAGE' // 设置商家列表当前分类
export const ADDCART = 'ADDCART' // 增加购物车商品
