export default {
  pages: [
    'pages/msite/index',
    'pages/login/index',
    'pages/register/index',
    'pages/profile/index',
    'pages/profile/info/index',
    'pages/profile/info/username/index',
    'pages/profile/info/password/index',
    'pages/profile/address/index',
    'pages/profile/address/add/index',
    'pages/profile/address/edit/index',
    'pages/profile/address/search/index',
    'pages/discover/index',
    'pages/order/index',
    'pages/order/detail/index',
    'pages/address/index',
    'pages/city/index',
    'pages/search/index',
    'pages/food/index',
    'pages/shop/index',
    'pages/clearing/index',
    'pages/test/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
}
